### ISSUE TITLE
no cube renders everything in black

### ISSUE THREAD

**Issue by mixo111** [Cadiboo/NoCubes#108]
I have been using this mod for 2 years and I have not had any problems, yesterday all the terrain textures turned black, but only when I activate this mod. I uninstalled Minecraft and reinstalled it but nothing, I also tried it without any other mods and different versions of your mods but nothing.
When I render the terrain with your mods, everything your mods render turns black, leaves, dirt, rocks... I need help, this mod is very important to me. Sorry for my English but I'm using Google Translate.

**Comment by Cadiboo** [comment]
This is a feature on older versions - for 24 hours every Halloween everything becomes black.  It’ll go back to normal tomorrow.  Newer versions of the mod do not have this feature.
If you really want to play today, you can change your computer’s date to a different day and NoCubes will not think it is Halloween anymore and the ground will no-longer be black.

FYI there is another of these events in June where the ground is rainbow :).

**Comment by mixo111** [comment]
This mod is very trolling, what a scare, I've been messing around with the game all morning and I can't believe this is it.
What a relief, because for me it is a great mod that gives an incredible visualization, thank you with all my heart for your quick response, I am now calm. Very good mod, essential for me.
