### ISSUE TITLE
error

### ISSUE THREAD

**Issue by FilipKompaniets** [Cadiboo/NoCubes#110]
The mod with Rubidium or Embedium does not work :( 
verzion: 1.20.1-0.5.0-dev-b81a6c5
Beta

**Comment by Cadiboo** [comment]
Rubidum isn’t supported (yet).  See https://github.com/Cadiboo/NoCubes/issues/88#issuecomment-1858375480 for more info.

**Comment by FilipKompaniets** [comment]
> Рубідум (поки що) не підтримується. Див. [#88 (коментар)](https://github.com/Cadiboo/NoCubes/issues/88#issuecomment-1858375480) для отримання додаткової інформації.

ok
