### ISSUE TITLE
How to customize the switch for smooth leaves？

### ISSUE THREAD

**Issue by mosheng1** [Cadiboo/NoCubes#111]
I am unable to find the relevant configuration for the leaves

<img width="773" alt="PixPin_2024-01-06_16-23-54" src="https://github.com/Cadiboo/NoCubes/assets/75206669/fcd8b0cd-fe4b-4ffd-b547-8292038fb10b">

**Comment by Cadiboo** [comment]
On 1.13+ smooth leaves has been merged into smooth terrain and is now handled by the server/world config.  You can change if a block is smooth or not by looking at it in-game and pressing the N key on your keyboard.  If you want to manually edit the config file, you can find it by running the following command in-game `/config showfile nocubes SERVER`.
