### ISSUE TITLE
Feature request: Hexagonal vozxelization

### ISSUE THREAD

**Issue by Orinai** [Cadiboo/NoCubes#112]
This is an entirely off-the-deep-end suggestion, but it occurred to me as an idea, and this is the only mod I am aware of that actually changes the voxels in any way, so I figured if there was any place to suggest it, here would be the case.

What if, rather than entirely smooth terrain, it were hexagonal prisms, like wargaming tile (heroscape/warhammer/etc...). It would be really cool to see minecraft transformed into something that resembles those playspaces.

I suspect this is probably harder than just smooth terrain ironically, since smooth can just add move polygons to the surface of cubic voxels, while hexagonal tiling would have to actually change voxels from cubes to hexagonal prisms in order to tile things along a hexagonal grid. But like I said, you are the only dev I have seen attempting to modify the voxels in any way, so if there was anywhere to suggest, this seemed like the best place.

**Comment by Cadiboo** [comment]
Very cool idea!  I’m currently watching the dev logs of Planetsmith, a game that does this, you may enjoy them (and the game) too.
I’m hardly the only dev to look into this, see the following videos:
- https://m.youtube.com/watch?v=QJSlhQzPiIM
- https://m.youtube.com/watch?v=mLONYQ4qHRA
- https://m.youtube.com/watch?v=oaZHhFayK8E
- https://m.youtube.com/watch?v=EbbnqD4HLqQ
- https://m.youtube.com/watch?v=MQ-rw2sVx28

Doing this properly requires changing the world format from cubic to hexagonal storage, as you said.
I’m not going to be doing that in NoCubes.
If you want to have a crack at doing just the visual changes, feel free to clone this repo and do some work on the mod, the file you would want to base your mesher off is CullingCubic.java.
