### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by LunarArmageddon99** [Cadiboo/NoCubes#113]
"[Render thread/FATAL] [mixin/]: Mixin apply failed mixins.nocubes.json:LevelRendererMixin -> net.minecraft.client.renderer.LevelRenderer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("CONSTANT") on net/minecraft/client/renderer/LevelRenderer::nocubes_setBlocksDirty with priority 1000 cannot inject into net/minecraft/client/renderer/LevelRenderer::m_109494_(IIIIII)V merged by me.jellysquid.mods.sodium.mixin.core.render.world.WorldRendererMixin with priority 1000 [PREINJECT Applicator Phase -> mixins.nocubes.json:LevelRendererMixin -> Prepare Injections ->  -> constant$zob000$nocubes_setBlocksDirty(I)I -> Prepare]"
This was the only error I could find when attempting to load NoCubes, Physics Mod and a couple other mods.  Strangely enough, the logs, well, uhh...
The first log duplicated itself (viewing them via the Modrinth launcher), the 'Today-1' log is tiny and improper, while the second log (from the same crash..?) is from... January 1, 2001
Next crash produced the same results, even after repairs and whatnot, except with the second log's date being February 1 2001, and this has continued so far.  (I wonder if I could get to 2002?)

When discussing this in the discord server for Embeddium, ModernFix and the like (also have both installed) I found and sent this error in the chat, and what I'm 99% sure is a bot 'fixed' the issue.  Here's what it has to say.
"Compilation Error:
! Missing $ inserted.
<inserted text> 
                $
l.50 ...ft/client/renderer/LevelRenderer::nocubes_
                                                  setBlocksDirty with priori...
I've inserted a begin-math/end-math symbol since I think
you left one out. Proceed, with fingers crossed.

LaTeX Font Info:    Trying to load font information for OT1+lmr on input line 5
0.
(/usr/local/texlive/2023/texmf-dist/tex/latex/lm/ot1lmr.fd"
Sending the next line got the same results.  I was unable to find any other errors in the latest (valid) log, but here it is if anyone else wants to go over it.  I don't really care about, what, my desktop name being revealed?
[debug-4.log.gz](https://github.com/Cadiboo/NoCubes/files/14769666/debug-4.log.gz)

**Comment by LunarArmageddon99** [comment]
I should also mention that I kept getting the following error with many variations between many mods;
"27Mar2024 02:48:02.784] [Render thread/DEBUG] [mixin/]: mixins.oculus.vertexformat.json:immediate.MixinLevelRenderer: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)"
I'm still trying to figure out if it's related, or if it even matters at all, but I'm putting it here in case it helps at all.

**Comment by LunarArmageddon99** [comment]
Have determined the root of the problem to be Embeddium

**Comment by Cadiboo** [comment]
Ah, right, now I remember why I hadn't closed #106 and #88 - I hadn't released the builds to curseforge yet.
I've just released version `1.20.1-0.5.1` which is compatible with Rubidum, Embeddium and Oculus, please download it from curseforge.

**Comment by Cadiboo** [comment]
> When discussing this in the discord server for Embeddium, ModernFix and the like (also have both installed) I found and sent this error in the chat, and what I'm 99% sure is a bot 'fixed' the issue. Here's what it has to say. "Compilation Error: ! Missing $ inserted. $ l.50 ...ft/client/renderer/LevelRenderer::nocubes_ setBlocksDirty with priori... I've inserted a begin-math/end-math symbol since I think you left one out. Proceed, with fingers crossed.
> 
> LaTeX Font Info: Trying to load font information for OT1+lmr on input line 5 0. (/usr/local/texlive/2023/texmf-dist/tex/latex/lm/ot1lmr.fd"

That's definitely a bot, it thinks you're trying to write LaTeX - see https://en.wikipedia.org/wiki/LaTeX#Example for more info
