### ISSUE TITLE
Origins Incompatibility

### ISSUE THREAD

**Issue by whiteglovian** [Cadiboo/NoCubes#119]
Yeah, one of my must-haves broke this mod unfortunately. When it crashes at the very beginning of the opening stages it doesn't have a crash log, but here's my ATLauncher log showing it crash with Origins, but not without
https://paste.atlauncher.com/view/02039a49-e689-4373-bf7f-b54e4b422ed6

**Comment by Cadiboo** [comment]
Fixed by https://github.com/Cadiboo/NoCubes/commit/d999a0f647fd5ab0f2a812ac40897017d73624c8
