### ISSUE TITLE
ExceptionInInitializerError on line 44 of ClientEventSubscriber.java

### ISSUE THREAD

**Issue by Cadiboo** [Cadiboo/NoCubes#15]
[crash-2019-01-12_12.14.40-client.txt](https://github.com/Cadiboo/NoCubes/files/2752828/crash-2019-01-12_12.14.40-client.txt)
[latest-2.log.txt](https://github.com/Cadiboo/NoCubes/files/2752831/latest-2.log.txt)

**Comment by ThePoshTux** [comment]
[crash-2019-01-13_17.57.00-client.txt](https://github.com/Cadiboo/NoCubes/files/2752889/crash-2019-01-13_17.57.00-client.txt)
[latest.log](https://github.com/Cadiboo/NoCubes/files/2752892/latest.log)

**Comment by Cadiboo** [comment]
fixed in 6b9c853
