### ISSUE TITLE
Buildings Look Odd 

### ISSUE THREAD

**Issue by WenXin20** [Cadiboo/NoCubes#28]
Forge v14.23.5.2810-1.12.2
No Cubes v0.2.6-pre1

Buildings can look weird with smooth blocks on, such as being able to see through the floor, or the desert temple. Is there any way that a config option could be added to allow smoothed blocks to connected to non-smoothed blocks? It might help with seeing through the floor where it wouldn't normally be possible.

Desert Temple: 
![2019-03-03_15 22 50](https://user-images.githubusercontent.com/12000593/53776789-c1efc200-3ebc-11e9-8a31-ce26f980b10d.png)

Minecolonies Builder Hut:
![2018-12-29_00 16 26](https://user-images.githubusercontent.com/12000593/53777158-f87a0c80-3ebd-11e9-9e06-e4fc14c1209d.png)

**Comment by Cadiboo** [comment]
This will be fixed with the reappearance of the OldNoCubes rendering algorithm (the same one as in NoCubes 1.7.2).

**Comment by Cadiboo** [comment]
OldNoCubes was added in 4bccdf8
