### ISSUE TITLE
South, West, and South-West facing surfaces have no texture in Marching Cubes

### ISSUE THREAD

**Issue by MineAndCraft12** [Cadiboo/NoCubes#3]
Putting this here to make it easier to track.

![image](https://user-images.githubusercontent.com/33556371/49612284-7b440780-f961-11e8-88f6-6ef4cd6910a3.png)

![image](https://user-images.githubusercontent.com/33556371/49612314-9282f500-f961-11e8-9269-c3c1a095f2aa.png)

**Comment by Cadiboo** [comment]
Should be an easy fix

**Comment by Cadiboo** [comment]
Fixed in latest build
