### ISSUE TITLE
Crash on Game Launch

### ISSUE THREAD

**Issue by WenXin20** [Cadiboo/NoCubes#30]
Minecraft v1.12.2
Forge v14.23.5.2836
NoCubes v0.2.8-Beta 6

It crashes when the game is launched.
[Crash Report](https://paste.dimdev.org/unewikadob.mccrash)

**Comment by Cadiboo** [comment]
Looks like the mod wasn’t properly built, I’ll look into it.

**Comment by Cadiboo** [comment]
Should be solved by commits f3bfd19d19bec580106e4d62006c94313a5ec412 to c22355d499.
[Download the working version](https://jitpack.io/com/github/Cadiboo/NoCubes/1.12.2-c22355d499-1/NoCubes-1.12.2-c22355d499-1.jar)

**Comment by Cadiboo** [comment]
Release: [1.12.2-0.2.8-pre6-jitpack](https://github.com/Cadiboo/NoCubes/releases/tag/1.12.2-0.2.8-pre6-jitpack)
