### ISSUE TITLE
Move the grass & flowers back to the ground

### ISSUE THREAD

**Issue by wdhwg001** [Cadiboo/NoCubes#32]
Now the grass & flowers sometimes partly float above the ground, which looks a bit weird.

I know it can be hard to fix, but perhaps it is possible to make those grass <1 block higher by "extending" them down on the ground.

**Comment by Cadiboo** [comment]
You want grass & flowers to be rendered starting lower than it actually is?

**Comment by wdhwg001** [comment]
Yes, and IMO it will look a bit better than partly floating perhaps?

**Comment by Jummit** [comment]
What could also be cool is making them stick to the normal vector of the ground, so they never float. That would be a bit tricky though, but it would look great!

**Comment by wdhwg001** [comment]
@Jummit But it will create empty grass/flower block, and that means more than 1 block in a block area. For me I would accept the "extend-to-the-ground" solution, although it will make small flowers and mushrooms look a bit weird.

Wait, is it possible to show a transparent grass/flower/mushroom when pointing to the exact block of them, and also stick them to the normal vector of the ground?

**Comment by Cadiboo** [comment]
I can’t dynamically change how the terrain looks depending on what you’re looking at without a _lot_ of overhead.
 Sticking them to the terrain below them would create selection boxes and blocks that don’t match where it appears to be at all. There is also not always terrain directly underneath, or even anywhere near, the block.
Both solutions would require manually rendering the block, which would be incompatible with any other mod that does stuff with block rendering (it wouldn’t crash, it just wouldn’t have the other mods changes applied). The best solution to this would be to stretch the block down a bit, but this is also very hard.

**Comment by wdhwg001** [comment]
How about changing the grass/flower/mushroom model? I mean, maybe we can make them have a model which is 2-block in height and lower than 1 block, but let them remain their 1 block size. This will make their models stick through the ground surface, but still look much better than floating.

**Comment by Cadiboo** [comment]
That would kill resource pack support. I think that I could modify the model as it is loaded and extend the lower elements of it down. It might looks strange but it wouldn’t be completely incompatible.

**Comment by wdhwg001** [comment]
I'm not sure, are there completely floating grass/flower/mushroom blocks that are not connecting with the ground on any edges? If not, how about moving the smaller model (mushroom etc.) to the closest attached edge inside the block first, and then extend them?

**Comment by Cadiboo** [comment]
Fixed as of 30645b09
