### ISSUE TITLE
NoCubes Crash

### ISSUE THREAD

**Issue by SpeakerHornet** [Cadiboo/NoCubes#34]
Forge: 14.23.5.2796
NoCubes: 1.12.2-0.2.9-pre1
RenderChunk rebuildChunk hooks: 1.12.2-0.3.1

No additional mods.

Log: https://paste.ee/p/K4Puc

**Comment by Cadiboo** [comment]
NoCubes above 0.2.8 does not require RenderChunk rebuildChunk Hooks And is incompatible with it

**Comment by SpeakerHornet** [comment]
Oh ok, thanks!

**Comment by Cadiboo** [comment]
I’ll see if I can add something to the dependencies of my mod that will cause a nicer crash

**Comment by SpeakerHornet** [comment]
it crashes without render chunk rebuild chunk hooks now.

https://paste.ee/p/WNLmY

**Comment by Cadiboo** [comment]
Well... I’ll fix that soon, I only tested it with OptiFine and CTM installed. The ASM code is a bit fragile because I backported it directly from 1.13

**Comment by Cadiboo** [comment]
Should be fixed in the latest

**Comment by MorePortal** [comment]
I have the same issue with the latest NoCubes(1.12.2-0.2.10-pre5) and latest Forge (14.23.5.2838)

https://gist.github.com/MorePortal/3c987cbeca34ba1c678e550781eb04ac

**Comment by Cadiboo** [comment]
This has been fixed in dev and will be fixed in the next prerelease
