### ISSUE TITLE
Collisions won't work

### ISSUE THREAD

**Issue by ELECTRO88888** [Cadiboo/NoCubes#35]
Hello again, It doesn't crash anymore, but, I manually have to add each block to the smoothable list thing, and I can't enable collisions... It tells me I am not on flat when I press C...

**Comment by Cadiboo** [comment]
What version?

**Comment by ELECTRO88888** [comment]
1.12.2

**Comment by ELECTRO88888** [comment]
The one you sent me

**Comment by Cadiboo** [comment]
1.12.2-0.2.7: Latest stable release, compatible with OptiFine, Vanilla and BetterFoliage
1.12.2-0.2.8-pre: Unstable collisions, compatible with OptiFine, Vanilla and BetterFoliage
1.12.2-0.2.9-pre: Backported from 1.13.2-0.2.9. Faster rendering. Compatible with OptiFine

1.13.2-0.2.9: Faster rendering, semi-stable collisions, compatible with Vanilla and theoretically OptiFine

**Comment by ELECTRO88888** [comment]
Ah okay, when do you think they will be? Also, great work on this mod, I have no clue how you manage to do all of this

**Comment by Cadiboo** [comment]
I’d say within the month, I’ve got a lot of stuff other than modding to deal with right now. Thanks!
