### ISSUE TITLE
Config file goes back to normal on load

### ISSUE THREAD

**Issue by dave1505** [Cadiboo/NoCubes#36]
When changing the config file to something I like in game and directly in the file everything goes well, but as soon as I startup the game, It changes the config file to default automatically and doesn't save the changes, is there anyway to resolve this?

**Comment by Cadiboo** [comment]
Fixed in [1.12.2-0.2.8-pre6\(https://jitpack.io/com/github/Cadiboo/NoCubes/1.12.2-c22355d499-1/NoCubes-1.12.2-c22355d499-1.jar). Its pretty unstable and work on back porting the 1.13.2 code to 1.12.2 is very slow.
