### ISSUE TITLE
Crash Before Game Launch

### ISSUE THREAD

**Issue by WenXin20** [Cadiboo/NoCubes#37]
Minecraft v1.12.2
Forge v14.23.5.2838
NoCubes v0.2.10-Pre 5

It crashes before the game is launched after pressing the green play button. The same happens with Pre 4.
[Crash Report](https://gist.github.com/WenXin20/1bebabc68a540061ac3ec6c771f18f09)

**Comment by Cadiboo** [comment]
Remove RenderChunk rebuildChunk Hooks

**Comment by WenXin20** [comment]
ok, that worked, thanks
