### ISSUE TITLE
Vertical Grass slopes affected by windshaders, causing tearing

### ISSUE THREAD

**Issue by MercuryDoll** [Cadiboo/NoCubes#39]
Tested with Optifine+SEUS
![2019-06-05_02 35 39](https://user-images.githubusercontent.com/7283216/59343256-bdcd0f00-8d0b-11e9-9832-ddaab8239a75.png)
![2019-06-05_02 41 43](https://user-images.githubusercontent.com/7283216/59343291-d2a9a280-8d0b-11e9-977a-ca91c610bbd5.png)

**Comment by Cadiboo** [comment]
Problem with SEUS.

**Comment by Cadiboo** [comment]
Also a cool gif of it from ages ago:
![Moving Grass](https://cdn.discordapp.com/attachments/531378009605931018/539301593615433758/movinggrass.gif "Moving Grass")

**Comment by ZzStormKnightzZ** [comment]
This hapens to me with SOUS

**Comment by Cadiboo** [comment]
I can't test it myself because SEUS doesn't work on my computer, but I think that you can fix it by editing the block ids in the shader. You can ask for help on the [Shader Labs Discord](https://discord.gg/RP8CEdB).
