### ISSUE TITLE
Cached Quads seems to pick random blocks

### ISSUE THREAD

**Issue by MineAndCraft12** [Cadiboo/NoCubes#4]
Cached Quads appears to select random blocks from within the chunk. These random blocks also seem to randomly change on occasion.

![image](https://user-images.githubusercontent.com/33556371/49612417-ec83ba80-f961-11e8-9334-be089bd32be0.png)

**Comment by Cadiboo** [comment]
Cache Quads caches the most recent quad with a real texture. I can update this to only cache smoothable block quads with real textures, but as it says in the tooltip, its a fix aimed at patching small hiccups in the algorithm - not fixing a pretty much broken one. I'll still see what I can do tho

**Comment by Eddi2015** [comment]
I also seem to get this issue with SurfaceNets 5:
First I noticed Bedrock randomly placed when digging some blocks:
![2018-12-09_19 45 38](https://user-images.githubusercontent.com/36605424/49701369-de48cf00-fbeb-11e8-83a6-f19b5b47e879.png)
Then I reloaded without NoCubes and RenderChunkRebuild to proof the misleading blocks:
![2018-12-09_19 47 07](https://user-images.githubusercontent.com/36605424/49701390-2a940f00-fbec-11e8-8d76-40fa4719843a.png)
And then I loaded back in with NoCubes and now there are normal blocks:
![2018-12-09_19 48 52](https://user-images.githubusercontent.com/36605424/49701402-4992a100-fbec-11e8-9855-2057d02a4966.png)
Here's my config:
![2018-12-09_19 49 08](https://user-images.githubusercontent.com/36605424/49701412-6202bb80-fbec-11e8-93b9-bdaf1ab52e69.png)

**Comment by Cadiboo** [comment]
Cache quads has been removed in 1ee0aa33da047c3707b95c2560564f53062d7c95
