### ISSUE TITLE
one block  "bridges" and arches invisible

### ISSUE THREAD

**Issue by MercuryDoll** [Cadiboo/NoCubes#40]
Happens with pretty much any type of block
![2019-06-05_02 46 56](https://user-images.githubusercontent.com/7283216/59343485-4946a000-8d0c-11e9-8911-4149774dc116.png)
![2019-06-05_02 46 49](https://user-images.githubusercontent.com/7283216/59343486-49df3680-8d0c-11e9-9e34-0e121dda6753.png)

**Comment by Cadiboo** [comment]
This is being worked on. You can currently use the OldNoCubes mesh generator that doesn't smooth blocks as much

**Comment by Cadiboo** [comment]
This has been fixed in the new nocubes for a while but I’m not sure if it’s been released yet

**Comment by Cadiboo** [comment]
Closed, see #66
