### ISSUE TITLE
Game Won't Load 1.14.2

### ISSUE THREAD

**Issue by Dragon0307** [Cadiboo/NoCubes#41]
When I try and run the latest version of Forge 1.14.2 and the mod's 1.14.2 build, the game crashes before it loads. The crash message is here:

The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game

PC Specifications:

8 GB RAM
64-Bit Intel Pentium 4415Y
Windows 10 Home 1803
Java 8 Version 201

Basically, I'm on a Surface Go

**Comment by Cadiboo** [comment]
Please post your logs. They are found in .minecraft/logs/. Your debug.log would be most helpful

**Comment by Dragon0307** [comment]
I have the debug.log here:
[debug.log](https://github.com/Cadiboo/NoCubes/files/3318456/debug.log)
I also have the crash log.gz, if it is going to be of any additional use.
[2019-06-22-3.log.gz](https://github.com/Cadiboo/NoCubes/files/3318457/2019-06-22-3.log.gz)

**Comment by Cadiboo** [comment]
> NullPointerException: Initializing game
	at net.minecraftforge.fml.packs.ResourcePackLoader.loadResourcePacks(ResourcePackLoader.java:58) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:62) ~[?:?] {pl:runtimedistcleaner:A}

This error isn’t caused by NoCubes. Quite a few people have been having it. I think it might be a Forge problem? It wasn’t happening on older Forge versions, so make sure you have the latest forge. You might also want to check the Forge GitHub for issue reports about this.
