### ISSUE TITLE
Crash on startup (no mods, only optifine)

### ISSUE THREAD

**Issue by Shootlife** [Cadiboo/NoCubes#45]
Ver. 1.12.2
Forge 2768

https://paste.ee/p/VqKXN

**Comment by Cadiboo** [comment]
I have no clue what is causing that error, but NoCubes requires Forge `2779` or later. Try updating and seeing if that solves your problem.
NoCubes is also only compatible with OptiFine greater or equal to `HD_U_E2` (You have `HD_U_E1`).
OptiFine `HD_U_E3` was made to work with Forge `2795` and I develop NoCubes for Forge `2795` and OptiFine `HD_U_E3`, so try updating to those versions and seeing if that solves your issue.
