### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by dave1505** [Cadiboo/NoCubes#46]
V. 1.12.2
Forge 2768

Likely a mod incompatibility

https://drive.google.com/open?id=12KRNfO06JQ7uXCCjKgyjtatwZJunQhXO

Sorry about the last crash report I sent, I just realized this error wasn't creating a crash report so I sent another random one I had

**Comment by Cadiboo** [comment]
NoCubes requires Forge `2779` or later to work.
