### ISSUE TITLE
Mod duplicates itself in the mod folder while ingame

### ISSUE THREAD

**Issue by Tsilliev** [Cadiboo/NoCubes#47]
Not sure why but only nocubes, duplicates itself (like a copy) in the mod folder, so next time I run vivecraft it crashes. I have to delete the copy each time before playing.

**Comment by Tsilliev** [comment]
Instead of deleting the newer copy I deleted the old and it stopped doing that, I also looked around and saw a mention of auto-updated in the other thread, I guess it was auto-updating. Am new to minecraft mods and didn't knew that!

**Comment by Cadiboo** [comment]
Interesting, it should be downloading the new one and deleting the old one. If you post your logs I might be able to find out why it couldn't delete the old file.
