### ISSUE TITLE
Falling through the ground

### ISSUE THREAD

**Issue by Tsilliev** [Cadiboo/NoCubes#48]
1. Mined some sand, the blocks started falling down and I fell through the ground
2. I put a bed next to a wall, upon wake up I fell through the ground

**Comment by Cadiboo** [comment]
What version? This isn't easily fixable, but in the latest versions you only fall 1 block into the ground and can get back out relatively easily.

**Comment by Cadiboo** [comment]
Fixed for 1.12.2 in 7d47881. 1.14.3 already contains this.

**Comment by Tsilliev** [comment]
Hello, I got the 0.3.2 version and I can confirm that I fell one block only, thank you!
