### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Recorpse** [Cadiboo/NoCubes#49]
It isn't even showing up in the mod list. I'm using Fabric with a few mods, optifine, and I'm using SE Path Tracing.

**Comment by Cadiboo** [comment]
Yeah, this is a Forge mod.

**Comment by Recorpse** [comment]
I was told it works with Fiber

**Comment by Cadiboo** [comment]
I don't know what Fiber is. If you mean Fabric, no - NoCubes is not written for Fabric.

**Comment by Recorpse** [comment]
thats what I meant
