### ISSUE TITLE
Grass not smoothed in OldNoCubes

### ISSUE THREAD

**Issue by MineAndCraft12** [Cadiboo/NoCubes#5]
![image](https://user-images.githubusercontent.com/33556371/49612926-5fd9fc00-f963-11e8-81c5-8712522c22ec.png)

**Comment by Cadiboo** [comment]
This is temporary while I fix a bug where the algorithm can't render grass at all. I'm looking into the cause

**Comment by Cadiboo** [comment]
fixed in commit f568ced28548f2013f5db068b7ce32b406ea361e
