### ISSUE TITLE
Crash on game launch and for some reason no report

### ISSUE THREAD

**Issue by STALKER-medved** [Cadiboo/NoCubes#50]
upon stating minecraft with my mods (plus the no cubes mod) the game crashes but offers no report so cant really solve the problem, i am open for help and tips!

**Comment by Cadiboo** [comment]
What Minecraft version are you using?
What Forge version are you using?
What NoCubes version are you using?
Please provide your `debug.log` or `latest.log` from `.minecraft/logs`

**Comment by STALKER-medved** [comment]
i am using the latest version for 1.12.2
i am using minecraft 1.12.2 
iam using the latest nocubes version

**Comment by STALKER-medved** [comment]
[2019-07-11-6.log.gz](https://github.com/Cadiboo/NoCubes/files/3384727/2019-07-11-6.log.gz)
[debug-5.log.gz](https://github.com/Cadiboo/NoCubes/files/3384728/debug-5.log.gz)
[latest.log](https://github.com/Cadiboo/NoCubes/files/3384729/latest.log)

**Comment by STALKER-medved** [comment]
please solve

**Comment by Cadiboo** [comment]
> Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.init.Items

Some other coremod is breaking the game. It could be any one of
- llibrary
- OptiFine
- ShoulderSurfing
Additionally, the version of Llibrary that you're using was written for 1.12, not 1.12.2. You should update it.

**Comment by STALKER-medved** [comment]
thanks!

**Comment by STALKER-medved** [comment]
you also might have solved two problems instead of one

**Comment by STALKER-medved** [comment]
Thanks anyway

**Comment by Cadiboo** [comment]
Good luck :+1:

**Comment by STALKER-medved** [comment]
i tried all of them, not a single one worked

**Comment by STALKER-medved** [comment]
it also still crashes the game just by itself

**Comment by STALKER-medved** [comment]
wait... does this mode have a dependency?

**Comment by STALKER-medved** [comment]
it doesnt

**Comment by Cadiboo** [comment]
> wait... does this mode have a dependency?

No
