### ISSUE TITLE
mod crashes game while touching smoothed blocks when OldNoCubes and collisions is on

### ISSUE THREAD

**Issue by Zunlite** [Cadiboo/NoCubes#51]
heres the crash log
https://paste.dimdev.org/isulimijux.mccrash

also, i just hopped on creative mode to experiment with the issue,  i placed a bunch of dirt in a water superflat world and found out that when the settings are on barely any of the blocks collided

**Comment by Cadiboo** [comment]
Fixed in 1.14.4. 1.12.2 will be updated to 0.4.0 soon.

**Comment by Cadiboo** [comment]
Closing as 1.12.2 is unsupported by Forge & if I do backport to be 1.12.2 it will be a full rewrite that will implicitly fix this issue.
