### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by kerocate** [Cadiboo/NoCubes#55]
When I use a mod like BOP, part of the square's surface is not only unflattering, but it also lowers my FPS to 10. Mod's version is 1.12.2-0.3.3

**Comment by kerocate** [comment]
This is an interesting finding, is it because this mod makes the square have more faces?

**Comment by Cadiboo** [comment]
Can you provide a screenshot? NoCubes changes the chunk rendering which is done off-thread so there should be no way for it to effect FPS.

**Comment by kerocate** [comment]
Please don't close this issue. I will be on a business trip few days. I will describe the issue in detail.

**Comment by Cadiboo** [comment]
Any progress on this?

**Comment by kerocate** [comment]
Oh, I am sorry that I forgot it. In the later tests I found that the problem did not exist anymore. I do not know why.
