### ISSUE TITLE
Minecraft crash on world join // Issue with Optifine 1.12.2

### ISSUE THREAD

**Issue by Clasher31HD** [Cadiboo/NoCubes#56]
When i want to create and join the world, my Minecraft crashes. This is the Log: https://pastebin.com/vw5ZcyEh can someone help me and tell me where the issue is? I think its because of Optifine, but how can I fix it?

**Comment by Cadiboo** [comment]
Yeah, it’s a problem with NoCubes<->OptiFine. NoCubes was designed for an older version of OptiFine. I’ll fix this when I get time.

**Comment by Cadiboo** [comment]
Should be fixed in 1.12.2-0.4.0-pre1
