### ISSUE TITLE
Crash on 1.14.4

### ISSUE THREAD

**Issue by VL4DST3R** [Cadiboo/NoCubes#57]
Crashes on the latest forge version. Fun fact: if loaded togetther with optifine, the game loads, but nocubes does nothing. https://pastebin.com/chCxGnCH

**Comment by Cadiboo** [comment]
> Fun fact: if loaded togetther with optifine, the game loads, but nocubes does nothing.

Problem with OptiFine<->Forge. Hopefully they fix it soon.

**Comment by Cadiboo** [comment]
Fixed in 1.14.4-0.4.0-pre5
