### ISSUE TITLE
Required Optifine Version for 1.12.2

### ISSUE THREAD

**Issue by WenXin20** [Cadiboo/NoCubes#58]
Minecraft v1.12.2
Forge v14.23.5.2838
No Cubes v0.4.0-pre1

No Cubes requests an Optifine version of at least HD U F, but the highest version available to 1.12.2 is HD U E3.

**Comment by Cadiboo** [comment]
[OptiFine Donloads](https://optifine.net/downloads) > Preview versions > [OptiFine 1.12.2 HD U F2 pre1](http://optifine.net/adloadx?f=preview_OptiFine_1.12.2_HD_U_F2_pre1.jar)

**Comment by WenXin20** [comment]
Thanks, didn't realize there was a pre version for 1.12.2
