### ISSUE TITLE
Incompatibility with DynamicLights from Optifine

### ISSUE THREAD

**Issue by Cadiboo** [Cadiboo/NoCubes#6]
With NoCubes:
![2018-12-07_15 42 29](https://user-images.githubusercontent.com/37298044/49628195-deec3480-fa36-11e8-952a-a5c668197b00.png)
Without NoCubes:
![2018-12-07_15 42 57](https://user-images.githubusercontent.com/37298044/49628202-ec092380-fa36-11e8-8197-572c0ca28f14.png)

**Comment by MineAndCraft12** [comment]
Note that Dynamic lights does work with most shaderpacks, but not without.

**Comment by Cadiboo** [comment]
I think its an issue with how I'm getting the brightnesses of the blocks

**Comment by Cadiboo** [comment]
fixed a while back
