### ISSUE TITLE
Nocubes don't work with optifine!

### ISSUE THREAD

**Issue by ItsJustAlex47** [Cadiboo/NoCubes#60]
When i start minecraft 1.12.2 with optifine and the nocubes mod the mod doesn't start because i need the F version of it (i have the E version) i changed version but i can't install the other mods i want to use.

**Comment by Cadiboo** [comment]
> the mod doesn't start because i need the F version of it (i have the E version)

If this is the problem please see https://github.com/Cadiboo/NoCubes/issues/58
> i can't install the other mods i want to use.

If this is the problem please specify which mods you can't use

**Comment by ItsJustAlex47** [comment]
Ok thanks, i installed the optifine pre version now the mod work.
