### ISSUE TITLE
Nocubes1.12.2-0.4.0-pre1 requires an incompatible optifine version

### ISSUE THREAD

**Issue by Shadowex3** [Cadiboo/NoCubes#63]
Nocubes1.12.2-0.4.0-pre1 for minecraft 1.12.2 refuses to load with an appropriate version of optifine, instead it requests a U-F version of optifine. The U-F releases are only compatible with minecraft 1.14.3 and up.

**Comment by Shadowex3** [comment]
Disregard, I was getting my mods from an unreliable source and going straight to optifine shows there IS an F version for 1.12.2

**Comment by Cadiboo** [comment]
Slightly related to #58
