### ISSUE TITLE
You must re-open the game to see the chnages if you tweak things in Mod Configuration

### ISSUE THREAD

**Issue by NitroxPower** [Cadiboo/NoCubes#65]
For example i dint want to have the short grass because it has some good performance impact so i disabled it but i had to re-open the game in order to see the chnages and i think this happens with any setting.

**Comment by Cadiboo** [comment]
If you change a config with the key binds it happens instantly.
If you change a config from the config menu it happens within about 10 seconds.
If you change it in the config file it happens when you launch the game
