### ISSUE TITLE
1x1 Hole isnt visible with smooth terrain

### ISSUE THREAD

**Issue by ScriptedAnar** [Cadiboo/NoCubes#66]
![image](https://user-images.githubusercontent.com/46358553/67761566-3844c400-fa4c-11e9-9265-1b2eabd00639.png)
![image](https://user-images.githubusercontent.com/46358553/67761610-4c88c100-fa4c-11e9-9e15-4859ccf91f53.png)

**Comment by Cadiboo** [comment]
This is fixed if you enable collisions (on 1.12.2/1.13.2, they don't work on 1.14.4 yet) or use the OldNoCubes renderer. This is going to be fixed soon:tm: by adding new mesh generators

**Comment by Cadiboo** [comment]
This has been fixed for ages in the 1.16 pre-releases
