### ISSUE TITLE
I don't see curve trees

### ISSUE THREAD

**Issue by TheSamden** [Cadiboo/NoCubes#69]
I've a problem with log and leaves block. They aren't curved. I already tried to disable my shaderpack but It doesn't work and I don't have ressource pack.. 
How to solve this bug ? 
Thx :) 
![2019-12-07_16 37 46](https://user-images.githubusercontent.com/58633308/70377132-3276b400-1911-11ea-8165-5624da450ba8.png)

**Comment by Cadiboo** [comment]
Go to your config and change the leaves rendering settings.
