### ISSUE TITLE
Crash with Cube Mod

### ISSUE THREAD

**Issue by 6ix7even** [Cadiboo/NoCubes#7]
When I install RenderChunk and NoCube, I play crash for no reason, I tried to launch them alone and it's the same thing

I do not see where the problem comes from

Crash Report ; https://pastebin.com/4D6Saup4

**Comment by Cadiboo** [comment]
The latest version of the coremod has everything repackaged, so it’s different from previous versions and won’t work with mods that depended on those versions. I’m putting out a new release of NoCubes today to fix this.
