### ISSUE TITLE
Water looking wrong underwater

### ISSUE THREAD

**Issue by dave1505** [Cadiboo/NoCubes#71]
Minecraft forge: 1.12.2-forge1.12.2-14.23.5.2847
Nocubes: NoCubes-1.12.2-0.4.0-pre1

Is this problem known and does this have a fix?

![2020-03-09_16 18 29](https://user-images.githubusercontent.com/34339148/76234740-06294700-6222-11ea-84c4-5cc629e0bb22.png)

**Comment by Cadiboo** [comment]
I believe it's fixed in more recent Minecraft versions, I'll see what I can do

**Comment by Cadiboo** [comment]
Fixed in the 1.16 code as of fc7a1e3d (not released yet but it will be)
