### ISSUE TITLE
Where do the js print() calls print?

### ISSUE THREAD

**Issue by EmmanuelMess** [Cadiboo/NoCubes#73]
https://github.com/Cadiboo/NoCubes/blob/2fc674b2462d2af85d4ae9e113582dccc303b186/src/main/resources/nocubes-transformer.js#L349

What does this print to?

**Comment by EmmanuelMess** [comment]
Nevermind, it prints to the `runClient` gradle task log.

**Comment by Cadigal-displayr** [comment]
Yeah, it prints to the log if it’s enabled. I think coremod output is disabled in a production environment though but it’s very useful for debugging.
