### ISSUE TITLE
Optifine With NoCubes 1.14.4 Crashes

### ISSUE THREAD

**Issue by Gittyuphub101** [Cadiboo/NoCubes#80]
I'm using optiforge, mixinbootstrap, nocubes, and optifine ofc and when I load it it gives me an optifine version error, so I know whats going on but I don't know how to fix it: optiforge and nocubes both need different version of optifine but idk how to fix that

**Comment by Cadiboo** [comment]
Why do you need OptiForge at all? IIRC OptiFine can load itself on Forge without issues on 1.14. Also, neither NoCubes, Forge & OptiFine require Mixins.
A screenshot of the error + your log would be helpful if that doesn’t fix the issue

**Comment by Cadiboo** [comment]
Closing this because of a lack of reply + it's for 1.14.4
