### ISSUE TITLE
1.16.5 - Game crashed while loading with exception message: java.lang.VerifyError: Bad local variable type

### ISSUE THREAD

**Issue by Lil-Allie-Astra** [Cadiboo/NoCubes#82]
https://gist.github.com/Lil-Allie-Astra/b2d439408049463d83dedf280c4a8e29

**Comment by Lil-Allie-Astra** [comment]
Interesting side note; my server will run with this version of NoCubes just fine*

*"fine" meaning "it's continues running, but keeps spamming the 'server overloaded' warning, skipping a notable amount of ticks each time.

**Comment by Cadiboo** [comment]
Hey, sorry for the late response. This was caused by using a version of OptiFine (a specific preview version) that NoCubes doesn't support. Using non-preview releases of OptiFine resolve this.
