### ISSUE TITLE
Crashes game when loading

### ISSUE THREAD

**Issue by MonarchGamingFB** [Cadiboo/NoCubes#83]
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game
Exit Code: -1

I got this when loading Minecraft up. Got the correct version (1.14.4) etc... just doesn't want me to load up.

**Comment by Cadiboo** [comment]
Sorry for the late response. When you ask for help please post the log from [.minecraft](https://minecrafthopper.net/help/finding-minecraft-data-folder/)/logs/latest.log. Without this info I can't really diagnose the problem so I'm closing this issue, 1.14.4 is also too old for me to support.
