### ISSUE TITLE
Compatibility with worlds using mostly non-vanilla blocks?

### ISSUE THREAD

**Issue by kotoroshinoto** [Cadiboo/NoCubes#84]
Will this work entirely client side, or does it have to be on the server?

How would it play with mods and modpacks using terrafirmacraft/gregtech/dynamic trees etc? I tossed it into the client with terrafirmagreg modpack and I am not seeing any effect at all.

**Comment by kotoroshinoto** [comment]
I have realized that I missed the controls for adding block types.

is there something to handle fluids? Terrafirmacraft replaced vanilla water

**Comment by Cadiboo** [comment]
> is there something to handle fluids? Terrafirmacraft replaced vanilla water

Not currently unfortunately, this is a known issue
