### ISSUE TITLE
Disable smoothing of the tree leaves

### ISSUE THREAD

**Issue by MiltonBain** [Cadiboo/NoCubes#90]
I cannot figure out how to disable the smoothing of the tree leaves.
I can press the hotkey "n" in game to temporarily disable it, but if I leave the game and join back, it is not disabled anymore.

If someone can point me in the direction of how to disable the smoothing of certain blocks, that would be great.
Thanks!

**Comment by Cadiboo** [comment]
The n hotkey is how smoothness is toggled. It should persist between leaving and joining the same world. If you want custom defaults for every world look into using forges defaultconfigs system.

**Comment by MiltonBain** [comment]
Here is a dropbox link to a video I recorded (sorry for any compression that occurred.)

[Video Link Here](https://www.dropbox.com/s/q78pld6j0n9arnc/No_Cubes_Demonstration%20%20Made%20with%20Clipchamp_1658678235627.mp4?dl=0)

Here's a link to the logs on dropbox.
[Log One](https://www.dropbox.com/s/0quos8zxvrqg8fw/2022-07-24-1.log?dl=0)
[Log Two](https://www.dropbox.com/s/maczs6sum0ymtgu/2022-07-24-2.log?dl=0)

It does seem that upon leaving and rejoining, it does stick, but if I quit the game and rejoin, the settings are then reset.

Secondly, I am unsure if this is a product of Minecraft or the rendering engine, but you can see in the video I had to kind of finesse it to smooth them out, and when I pressed the 'n' hotkey, it did not get all the leaves on that tree.

Thirdly, I noticed that in "saves/[world_name]/serverconfig" is where the mod file writes the configuration to, nocubes-server.toml. Is there a way to edit the blacklist manually? I tried putting in "minecraft:oak_leaves" and whatnot but that did not seem to change anything.
Looking into that further I noticed each blacklisted item had 2 more fields, [range, persistence]. What exactly do these do?

**Comment by Cadiboo** [comment]
I don’t have time right now but I’ll take a look at the video and logs in the next couple days.

> I tried putting in "minecraft:oak_leaves" and whatnot but that did not seem to change anything. Looking into that further I noticed each blacklisted item had 2 more fields, [range, persistence]. What exactly do these do?

The lists in the config store blockstate identifiers, not block identifiers. So putting “oak_leaves” into the list only affects one of the multiple block states, you’ll need to fill out all of the possible variants you want smoothed. The n key does this automatically for you (it adds all blockstates for the block you’re looking at, unless you’re pressing shift). You can read more about these specific properties at https://minecraft.fandom.com/wiki/Leaves
![F294F4EF-1E16-4DE6-A569-83A7FB15D8BD](https://user-images.githubusercontent.com/37298044/181648154-be3e6661-fc0b-494a-831f-e9d1a92e0dd3.png)

**Comment by Cadiboo** [comment]
@MiltonBain It looks like you're using a release (`fe6e9dea`) from before the config issue was fixed. Please upgrade
<img width="903" alt="Screen Shot 2022-08-13 at 12 42 06 pm" src="https://user-images.githubusercontent.com/37298044/184465492-c46c150d-94c8-46be-9c80-02a88acfacff.png">
