### ISSUE TITLE
Mod Blocks not supported

### ISSUE THREAD

**Issue by 9182736450typist** [Cadiboo/NoCubes#92]
Mod blocks are still in cubes!

**Comment by SodiumZH** [comment]
Seemingly only some blocks in a certain list appliy non-cube features (e.g. dirt, sand, stone,..), and blocks are still in cubes by default. I'm not sure if it can be configured to add more custom blocks to this list...

**Comment by Cadiboo** [comment]
Look at the block you want to make smooth in-game and press ‘n’.
