### ISSUE TITLE
World generation issue with TerraForged and NoCubes in 1.16.5

### ISSUE THREAD

**Issue by LoserCard** [Cadiboo/NoCubes#97]
There seems to be an issue with world generation when using TerraForged (0.2.16) and NoCubes (0.5.0-dev-8327c6d5) in Minecraft 1.16.5. When generating the world using TerraForged+NoCubes, a majority of the biomes are converted to stone on the surface levels (i.e. does not generate any trees, dirt, or foliage). World pregeneration using TerraForged without NoCubes seems to workaround the issue but any newly generated chunks are affected once NoCubes is enabled.

**Comment by Cadiboo** [comment]
Does it happen on 1.19.3?

**Comment by LoserCard** [comment]
TerraForged is only released up to 1.16.5.

**Comment by Cadiboo** [comment]
1. What happens when you start a world with both mods installed and then remove nocubes?  Does terrain start having dirt after nocubes is removed?
2. 2. Please report this issue to TerraForged, I don’t currently have spare time to dedicate any effort to older versions.

**Comment by Cadiboo** [comment]
I'm not going to be backporting changes to 1.16.5, closing this
